dset:
  train: /cs/usr/yair.shemer/AudioLab/encodec/egs/valentini/tr
  valid: /cs/usr/yair.shemer/AudioLab/encodec/egs/valentini/cv
  test: /cs/usr/yair.shemer/AudioLab/encodec/egs/valentini/tt
  matching: sort
batch_size: 32